In [8]:
import numpy as np

arr1= np.array([1,2,3,4,5,6])
arr2= np.array([7,8,9,10,11,12])

In [11]:
type(arr1)

numpy.ndarray

In [13]:
arr1.shape 
#single dimension array

(6,)

In [20]:
arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
arr1.reshape(2,3,1) #its a 3D

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [25]:
arr2 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

In [28]:
arr2.shape

(2, 6)

In [31]:
np.arange(0,10,2).reshape(1,5)

array([[0, 2, 4, 6, 8]])

In [60]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [61]:
##identity matrix or array 

a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
a.ndim

2

In [65]:
a.itemsize

8

In [66]:
a.dtype

dtype('float64')

In [67]:
##vectorized operations

arr1 =np.array([1,2,3,4,5,6])
arr2 =np.array([7,8,9,10,11,12])

In [71]:
#elementwise addition
print(arr1+arr2)
print(arr1-arr2)
#mukltiplication
print(arr1*arr2)
#division
print(arr1/arr2)

[ 8 10 12 14 16 18]
[-6 -6 -6 -6 -6 -6]
[ 7 16 27 40 55 72]
[0.14285714 0.25       0.33333333 0.4        0.45454545 0.5       ]


In [77]:
#universal functions

arr = np.array([4,4,4,4,4,5])

np.sqrt(arr)

array([2.        , 2.        , 2.        , 2.        , 2.        ,
       2.23606798])

In [78]:
np.exp(arr)
np.sin(arr)
np.amax(arr)

np.int64(5)

In [84]:
#slicing and indexing in numpy

arr3=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18]])
arr3.shape
print(arr3)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [90]:
print(arr3[2,2])

15


In [91]:
arr3[2][2]

np.int64(15)

In [97]:
# slicing operation
arr3[1:,2:]

array([[ 9, 10, 11, 12],
       [15, 16, 17, 18]])

In [98]:
arr3[1:]

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [99]:
#modify array elements

arr3

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [100]:
arr3[0,0]=100

In [101]:
arr3

array([[100,   2,   3,   4,   5,   6],
       [  7,   8,   9,  10,  11,  12],
       [ 13,  14,  15,  16,  17,  18]])

In [102]:
arr3[1:]=100

In [103]:
arr3

array([[100,   2,   3,   4,   5,   6],
       [100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100]])

In [106]:
#statistical operations
## to have mean as 0 and stadard deviation as 1

data= np.array([1,2,3,4,5,6,7,8,9,10])

mean = print(np.mean(data))
std = print(np.std(data))
variance= print(np.var(data))
median = print(np.median(data))

5.5
2.8722813232690143
8.25
5.5


In [113]:
n= (data-np.mean(data))/np.std(data)
#normalization
n

array([-1.5666989 , -1.21854359, -0.87038828, -0.52223297, -0.17407766,
        0.17407766,  0.52223297,  0.87038828,  1.21854359,  1.5666989 ])

In [120]:
arr[(arr<5) | (arr<5)]  #filtering

array([4, 4, 4, 4, 4])

In [123]:
import pandas as pd

In [127]:
data=[1,2,3,4,5,6,7,8,9,10]

In [131]:
type(data) 

numpy.ndarray

In [133]:
#it is always 1D array
ser=pd.Series(data)
type(ser)

pandas.core.series.Series

In [135]:
df=pd.DataFrame(data)
df

0
0   1
1   2
2   3
3   4
4   5
5   6
6   7
7   8
8   9
9  10

In [137]:
dic = {'name':['Tom', 'Jerry', 'Mickey', 'Donald'],
        
        'age':[10,20,30,40]}

ser1=pd.Series(dic)
ser1

name    [Tom, Jerry, Mickey, Donald]
age                 [10, 20, 30, 40]
dtype: object

In [139]:
df1=pd.DataFrame(dic)
df1

name  age
0     Tom   10
1   Jerry   20
2  Mickey   30
3  Donald   40

In [147]:
data=[1,3,4,5]
index=['a','b','c','d']

x=pd.Series(data,index)
x

a    1
b    3
c    4
d    5
dtype: int64

In [149]:
d={'a':1,'b':2,'c':3,'d':4}
y=pd.DataFrame(d,index)
y

a  b  c  d
a  1  2  3  4
b  1  2  3  4
c  1  2  3  4
d  1  2  3  4

In [154]:
#create a dataframe from a list of dictionaries

u = [{'name':[1,2],'tet':2},{'gaga':3,'ga':4,'cre':5}]

df2=pd.DataFrame(u)

df2

name  tet  gaga   ga  cre
0  [1, 2]  2.0   NaN  NaN  NaN
1     NaN  NaN   3.0  4.0  5.0

In [156]:
import numpy as np
np.array(u)


array([{'name': [1, 2], 'tet': 2}, {'gaga': 3, 'ga': 4, 'cre': 5}],
      dtype=object)

In [196]:
data3 = [{'Name':'Tom','Age':10,'City':'NY'},
         {'Name':'Jerry','Age':20,'City':'LA'},
         {'Name':'Mickey','Age':30,'City':'SF'},
         {'Name':'Donald','Age':40,'City':'SD'}]

In [211]:
df3=pd.DataFrame(data3,index=['a','b','c','d'])

In [212]:
df3


Name  Age City
a     Tom   10   NY
b   Jerry   20   LA
c  Mickey   30   SF
d  Donald   40   SD

In [213]:
type(df3['Name'])

pandas.core.series.Series

In [216]:
df3.loc['d']

Name    Donald
Age         40
City        SD
Name: d, dtype: object

In [217]:
#loc is location based indexing if it has some meaningfull label and iloc is integer based indexing

#accessing specific elements



Index(['a', 'b', 'c', 'd'], dtype='object')

In [220]:
df3=pd.DataFrame(data3,index=range(1,5))

In [221]:
df3

Name  Age City
1     Tom   10   NY
2   Jerry   20   LA
3  Mickey   30   SF
4  Donald   40   SD

In [223]:
#accesing specific eleemnt
df3.at[3,'City']

'SF'

In [225]:
df3.iat[2,2]

'SF'

In [235]:
#data manipulation with dataframe

df3['Salary']=[20,30,40,50]

In [236]:
df3

Name  Age City  Salary
1     Tom   10   NY      20
2   Jerry   20   LA      30
3  Mickey   30   SF      40
4  Donald   40   SD      50

In [237]:
df3.drop('Salary',axis=1,inplace=True)

In [241]:
df3['Age']=df3['Age']+12

In [242]:
df3

Name  Age City
1     Tom   34   NY
2   Jerry   44   LA
3  Mickey   54   SF
4  Donald   64   SD

In [247]:
df3.drop(1)

Name  Age City
2   Jerry   44   LA
3  Mickey   54   SF
4  Donald   64   SD

In [249]:
df3.drop(1,inplace=True,axis=0)

In [250]:
df3

Name  Age City
2   Jerry   44   LA
3  Mickey   54   SF
4  Donald   64   SD

In [298]:
df=pd.read_csv('data.csv')
df.head()

Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [299]:
df.tail()

Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [300]:
df.describe()

Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [301]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Date      50 non-null     object 
 1   Category  50 non-null     object 
 2   Value     47 non-null     float64
 3   Product   50 non-null     object 
 4   Sales     46 non-null     float64
 5   Region    50 non-null     object 
dtypes: float64(2), object(4)
memory usage: 2.5+ KB


In [302]:
df.dtypes

Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

In [303]:
#handing missing values

df.isnull().any(axis=0)

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

In [304]:
#how many missing value
df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [305]:
#filloing the values withe mean value

df['Sales_Fill_NA']=df['Sales'].fillna(df['Sales'].mean())

In [282]:
df.head()

Date Category  Value   Product  Sales Region  Sales_Fill_NA
0  2023-01-01        A   28.0  Product1  754.0   East          754.0
1  2023-01-02        B   39.0  Product3  110.0  North          110.0
2  2023-01-03        C   32.0  Product2  398.0   East          398.0
3  2023-01-04        B    8.0  Product1  522.0   East          522.0
4  2023-01-05        B   26.0  Product3  869.0  North          869.0

In [285]:
## Renaming col

df.rename(columns={'Date':'Sales Date'}).head()

Sales Date Category  Value   Product  Sales Region  Sales_Fill_NA
0  2023-01-01        A   28.0  Product1  754.0   East          754.0
1  2023-01-02        B   39.0  Product3  110.0  North          110.0
2  2023-01-03        C   32.0  Product2  398.0   East          398.0
3  2023-01-04        B    8.0  Product1  522.0   East          522.0
4  2023-01-05        B   26.0  Product3  869.0  North          869.0

In [306]:
## change dtypes

df['Value_new']=df['Value'].fillna(df['Value'].mean()).astype('int32')

In [309]:
df.head()

Date Category  Value   Product  Sales Region  Sales_Fill_NA  \
0  2023-01-01        A   28.0  Product1  754.0   East          754.0   
1  2023-01-02        B   39.0  Product3  110.0  North          110.0   
2  2023-01-03        C   32.0  Product2  398.0   East          398.0   
3  2023-01-04        B    8.0  Product1  522.0   East          522.0   
4  2023-01-05        B   26.0  Product3  869.0  North          869.0   

   Value_new  
0         28  
1         39  
2         32  
3          8  
4         26

In [313]:
#applying funtion

df['Value_new']=df['Value'].apply(lambda x:x*2)

In [314]:
df.head()

Date Category  Value   Product  Sales Region  Sales_Fill_NA  \
0  2023-01-01        A   28.0  Product1  754.0   East          754.0   
1  2023-01-02        B   39.0  Product3  110.0  North          110.0   
2  2023-01-03        C   32.0  Product2  398.0   East          398.0   
3  2023-01-04        B    8.0  Product1  522.0   East          522.0   
4  2023-01-05        B   26.0  Product3  869.0  North          869.0   

   Value_new  
0       56.0  
1       78.0  
2       64.0  
3       16.0  
4       52.0

In [316]:
grouped_mean=df.groupby('Product')['Value'].mean()
grouped_mean

Product
Product1    46.214286
Product2    52.800000
Product3    55.166667
Name: Value, dtype: float64

In [317]:
df.groupby(['Product','Region'])['Value'].sum()

Product   Region
Product1  East      292.0
          North       9.0
          South     100.0
          West      246.0
Product2  East       56.0
          North     127.0
          South     181.0
          West      428.0
Product3  East      202.0
          North     203.0
          South     215.0
          West      373.0
Name: Value, dtype: float64

In [318]:
#aggregate multiple functions

df.groupby('Region')['Value'].agg(['mean','sum','count'])

mean     sum  count
Region                          
East    42.307692   550.0     13
North   37.666667   339.0      9
South   62.000000   496.0      8
West    61.588235  1047.0     17

In [10]:
#mergin and joinging data frames

import pandas as pd
df1=pd.DataFrame({'Key':['A','B','C'],'Value1':[1,2,3]})
df2=pd.DataFrame({'Key':['A','B','F'],'Value2':[4,5,6]})

In [11]:
df2

Key  Value2
0   A       4
1   B       5
2   F       6

In [15]:
##merging dataframe with key 

df_merge=pd.merge(df1,df2,on='Key',how='right')
df_merge

Key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   F     NaN       6

In [16]:
import pandas as pd
from io import StringIO
Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'

df=pd.read_json(StringIO(Data))

In [19]:
df

employee_name            email  \
0         James  james@gmail.com   

                                         job_profile  
0  {'title1': 'Team Lead', 'title2': 'Sr. Develop...

In [21]:
#converting again to json
df.to_json()

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [24]:
df.to_json(orient='records')

'[{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}]'

In [27]:
df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",header=None)

In [28]:
df.to_csv('wine_new.csv')

In [30]:
!pip install lxml

   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   ---------------------------------------- 3.8/3.8 MB 38.2 MB/s eta 0:00:00


In [42]:
#read html file 

df=pd.read_html("https://www.fdic.gov/bank-failures/failed-bank-list")

In [50]:
#here you will get the 0th element of list becasue the output will be list from html
df[0].head()

Bank Name           City         State   Cert  \
0     The First National Bank of Lindsay        Lindsay      Oklahoma   4134   
1  Republic First Bank dba Republic Bank   Philadelphia  Pennsylvania  27332   
2                          Citizens Bank       Sac City          Iowa   8758   
3               Heartland Tri-State Bank        Elkhart        Kansas  25851   
4                    First Republic Bank  San Francisco    California  59017   

                 Aquiring Institution      Closing Date  Fund  Sort ascending  
0  First Bank & Trust Co., Duncan, OK  October 18, 2024                 10547  
1   Fulton Bank, National Association    April 26, 2024                 10546  
2           Iowa Trust & Savings Bank  November 3, 2023                 10545  
3              Dream First Bank, N.A.     July 28, 2023                 10544  
4           JPMorgan Chase Bank, N.A.       May 1, 2023                 10543

In [56]:
#match keyword is any col name or key of the table
df1=pd.read_html("https://simple.wikipedia.org/wiki/Corruption_Perceptions_Index",match='Nation')

In [57]:
df1[0].head()

Rank       Nation  2013  2012  2011  2010
0     1      Denmark   9.1   9.0   9.4   9.3
1     2  New Zealand   9.1   9.0   9.5   9.3
2     3      Finland   8.9   9.0   9.4   9.2
3     4       Sweden   8.9   8.8   9.3   9.2
4     5    Singapore   8.6   8.7   9.2   9.3

In [59]:
! pip install openpyxl

In [60]:
#converting the pickle file 
df_excel=pd.read_excel('data.xlsx')
df_excel

Name  Age
0  Krish   32
1   Jack   34
2   John   31

In [61]:
df_excel.to_pickle('pick_file')

In [62]:
pd.read_pickle('pick_file')

Name  Age
0  Krish   32
1   Jack   34
2   John   31